name: Auto merge main into gh-pages

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        
    - name: List all branches
      run: |
        git fetch --all
        git branch -a
    
    - name: Create gh-pages branch if it does not exist
      run: |
        if git show-ref --quiet refs/heads/gh-pages; then
          echo "Branch gh-pages exists."
        else
          echo "Branch gh-pages does not exist. Creating branch."
          git checkout -b gh-pages
          git push origin gh-pages
        fi
    
    - name: Checkout gh-pages branch
      run: git checkout gh-pages
    
    - name: Merge main into gh-pages
      run: git merge main
    
    - name: Push changes
      run: git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}